### ISSUE TITLE
namespaces with double colons bug.

### ISSUE THREAD

**Issue by DanielSollis** [rotationalio/honu#14]
Fix the issue where LevelDBEngine.Iter currently grabs the namespace by splitting on double colons (::). In the case of a namespace called for example "namespace::with::colons", Iter considers the namespace to be "namespace" and will not access the database correctly. As for a possible solution, with PR #12 the namespace is stored in the iterator, meaning we would no longer need to split on double colons. The following tests are currently skipping double colon test cases and need to be amended:

- engines/leveldb/leveldb_test: TestLevelDBIter line 163
- honu_test:  TestLevelDBInteractions line 119

**Comment by bbengfort** [comment]
Fixed by #21
