### ISSUE TITLE
[TESTING] fuzz testing for versions_test

### ISSUE THREAD

**Issue by eggyhead** [rotationalio/honu#24]
We want to increase confidence in the `versions` code by testing edge cases. A powerful tool for this is [fuzz testing](https://go.dev/security/fuzz/)

- [ ] Implement a Fuzz test in [`versions_test`](https://github.com/rotationalio/honu/blob/main/versions_test.go)

**Comment by eggyhead** [comment]
UPDATE 10/11/22: @eggyhead created a branch to work on this issue
unfortunate limitation of fuzz testing:

> The fuzzing arguments can only be the following types:
> string, []byte
> int, int8, int16, int32/rune, int64
> uint, uint8/byte, uint16, uint32, uint64
> float32, float64
> bool

there are plugin libraries which can support more complex data types, looking into options

**Comment by bbengfort** [comment]
Sounds like a good topic for a blog post!

**Comment by eggyhead** [comment]
```
remote: Permission to rotationalio/honu.git denied to eggyhead.
fatal: unable to access 'https://github.com/rotationalio/honu.git/': The requested URL returned error: 403
```

looks like I don't have permissions to push to a branch. What's your recommended way to contribute? Thanks!

**Comment by eggyhead** [comment]
this is the library I'm considering on adding for testing structs: https://github.com/AdaLogics/go-fuzz-headers#projects-that-use-go-fuzz-headers

**Comment by rebeccabilbro** [comment]
Hello @eggyhead and sorry for the slow response! Would you mind forking the honu repo and then opening PRs from branches off of your honu fork? 

The `go-fuzz-headers` project looks promising!
